# This is a basic workflow to help you get started with Actions

name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Build Dependencies
        run: |
          sudo chmod +x ./scripts/install_dependencies.sh
          ./scripts/install_dependencies.sh
        shell: bash
      - name: Build with LLVM
        run: |
          sudo chmod +x ./scripts/lint.sh
          ./scripts/lint.sh
        shell: bash

#build check jobs
  build-clang:
    name: Clang Ubuntu/Linux Build Check
    runs-on: ubuntu-latest
    needs: style-check
    steps:
      - uses: actions/checkout@v3
      - name: Setup Build Dependencies
        run: |
          sudo chmod +x ./scripts/install_dependencies.sh
          ./scripts/install_dependencies.sh
        shell: bash
      - name: Build with LLVM
        run: |
          sudo chmod +x ./scripts/build.sh
          ./scripts/build.sh
        shell: bash

  build-gcc:
    name: GCC Ubuntu/Linux Build Check
    runs-on: ubuntu-latest
    needs: style-check
    steps:
      - uses: actions/checkout@v3
      - name: Setup Build Dependencies
        run: |
          sudo chmod +x ./scripts/install_dependencies.sh
          ./scripts/install_dependencies.sh
        shell: bash
      - name: Build with LLVM
        run: |
          sudo chmod +x ./scripts/build.sh
          ./scripts/build.sh
        shell: bash

  build-msvc-windows:
    name: MSVC Windows Build Check
    runs-on: windows-latest
    needs: style-check
    steps:
      - uses: actions/checkout@v3
      - name: Install Winget Package Manager
        run: |
          $ProgressPreference='Silent'
          Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\MicrosoftDesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
          Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
        shell: pwsh
      - name: Setup Build Dependencies
        run: |
          ./scripts/install_dependencies.ps1
        shell: bash
      - name: Build with LLVM
        run: |
          ./scripts/build.ps1
        shell: pwsh
